name: Build and Package

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Bootstrap
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Theos
        run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/roothide/theos/master/bin/install-theos)"

      - name: Setup Environment
        run: echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Clone Repository
        run: git clone https://github.com/RootHide/Bootstrap.git

      - name: Make Bootstrap Package
        run: make package
        working-directory: Bootstrap

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Bootstrap.tipa
          path: ./Bootstrap/packages/Bootstrap.tipa
