name: Build and Package

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Bootstrap
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install Theos
        run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/roothide/theos/master/bin/install-theos)"

      - name: Install Make
        run: brew install make

      - name: Setup Environment
        run: echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Clone Repository
        run: git clone https://github.com/roothide/Bootstrap/

      - name: Make Bootstrap Package
        run: gmake -j$(sysctl -n hw.ncpu) package
        working-directory: Bootstrap

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Bootstrap.tipa
          path: ./Bootstrap/packages/Bootstrap.tipa

  update-readme:
    name: Update README.md
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: Zhou-Shilin/Bootstrap-Daily-ActionsBuilds
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Date and Time
        run: echo "DATE_TIME=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV

      - name: Edit README.md
        run: |
          sed -i "s/Last build:.*/Last build: $DATE_TIME/g" README.md

      - name: Commit and Push
        run: |
          git config --global user.name "GithubActions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update README.md"
          git push
